### ISSUE TITLE
Breaking change in @amplitude/analytics-browser@2.12.1

### ISSUE THREAD

**Issue by vtertre** [amplitude/Amplitude-TypeScript#1004]
## Expected Behavior
No breaking change in a patch version.

## Current Behavior
App build is broken.

## Steps to Reproduce

This code builds with `"@amplitude/analytics-browser@2.12.0"`.
It does not with `"@amplitude/analytics-browser@2.12.1"`.
```typescript
import { Types } from '@amplitude/analytics-browser';

const test = { level: Types.LogLevel.Debug };

function isCustomTrackingEvent({ event_type }: Types.Event): boolean {
  return (
    event_type !== Types.SpecialEventType.IDENTIFY &&
    event_type !== Types.SpecialEventType.GROUP_IDENTIFY &&
    event_type !== Types.SpecialEventType.REVENUE
  );
}
```

![Image](https://github.com/user-attachments/assets/15b0f0bc-144d-46c9-909d-26bf67531523)

## Environment
- JS SDK Version: `"@amplitude/analytics-browser@2.12.1"`
- Installation Method: Yarn
- Typescript 5.6.3

**Comment by Mercy811** [comment]
Hi @vtertre, `@amplitude/analytics-browser@2.12.2` should fix this.

**Comment by vtertre** [comment]
Hi @Mercy811 , thank you for the fix. However apparently the `ServerZone` enum usage is still broken.
We are using the `@amplitude/ampli@1.36.2` which generates an amplitude wrapper that does not compile with the changes introduced in `@amplitude/analytics-browser@2.12.1`.
Shall i create another issue?

**Comment by Mercy811** [comment]
Hi @vtertre, @amplitude/analytics-browser@2.13.0 should fix this.
